### ISSUE TITLE
Need to add "--all_load & --ObjC" linker flags

### ISSUE THREAD

**Issue by chiefy** [newyankeecodeshop/GAJavaScript#1]
I was banging my head on the wall trying to get this to work and then duh - I totally forgot about using static libs and using the --all_load and --ObjC linker flags. Might want to add something about that on the readme.md. Thanks for your work in this project!

**Comment by newyankeecodeshop** [comment]
Good catch - I just pushed up a note about that.

**Comment by chiefy** [comment]
Thanks - hopefully it will help someone in the future, and perhaps save a few crushed keyboards.

**Comment by newyankeecodeshop** [comment]
Right - developers will be crushing their keyboards over UIWebView itself. :-)

AHG
