### ISSUE TITLE
Block callback args corrupted when arrays are passed

### ISSUE THREAD

**Issue by ghost** [newyankeecodeshop/GAJavaScript#3]
Given some javascript that takes a callback function with three arguments, the second of which is an array:

``` javascript

function someCoolFunction (obj) {

    /* ... */

    obj.callback('First arg', [1, 2, 3], 'third arg');
}
```

Using GAJavaScript to call "someCoolFunction":

``` objc

GAScriptEngine* scriptEngine = [self scriptEngine];

GAScriptObject* obj = [scriptEngine newScriptObject];
[obj setFunctionForKey:@"callback" withBlock:^(NSArray* arguments) 
{
    assert([arguments count] == 3);     // fails
}];

[scriptEngine callFunction:@"someCoolFunction" withObject:obj];
```

The number of arguments is actually 5. The middle array is flattened out into the entire argument list.

**Comment by newyankeecodeshop** [comment]
Fixed this by passing array arguments as an object. This seemed safer than changing the simple value encoding to support nesting of arrays.
