### ISSUE TITLE
Multiple UIWebView / GAScriptEngine & Caching Issues

### ISSUE THREAD

**Issue by chiefy** [newyankeecodeshop/GAJavaScript#5]
I am working on a project which has 7-9 UIWebViews each with their own GAScriptEngine. I was having a problem where only the last rendered one would work properly. It turns out that if I didn't use a proper caching policy with my NSURLRequest it would work this way. Not sure what a good workaround is but FYI.

**Comment by newyankeecodeshop** [comment]
Is there a test case I can try to reproduce this? I usually use GAJavaScript in projects with HTML/JS files in the main bundle, so I haven't had much experience with caching policy and UIWebView. Is there a way I could reproduce the issues you're having? Are the UIWebViews' URLs public?

**Comment by chiefy** [comment]
Yeah - it's a weird issue that had me banging my head against the wall for a few hours :) I will try to fork and push a test-case tomorrow. I think now that I know the issue it's easy to reproduce. Anyhow, thanks so much for your work on this - definitely going to save some time for us.

**Comment by chiefy** [comment]
Ok, after some more investigation it doesn't appear the caching thing is the issue.
